hero section oluşturuldu
archis-academy/july-frontend-coral-buy-1 pull request #6
Opened 2024-07-22 10:08 UTC by kubrakaramanli

2024-07-23 16:57 UTC, MehmetSunguralp requested changes
Yorumlardaki değişiklikleri güncelle, font kalınlıklarını da değiştirmelisin

2024-07-23 16:57 UTC, MehmetSunguralp commented on images/andrey-zvyagintsev-EQj1ZMpq_VM-unsplash 1.png
Bu resime bu section'da ihtiyacın yok silebilirsin

2024-07-23 16:57 UTC, MehmetSunguralp commented on index.html
> +		<div class="main">
class adı olarak main yerine hero-section verebilirsin

2024-07-23 16:57 UTC, MehmetSunguralp commented on index.html
> +		<h1 class="h3">You Can Explore And Shop Many Different Collection From Various Brands Here. </h1>
class isimlerini daha anlamlı yazalım

2024-07-23 16:57 UTC, MehmetSunguralp commented on images/person.svg
Bu resmi svg yerine png olarak export edelim. resimleri png, şekiller svg olarak export edelim

2024-07-23 16:57 UTC, MehmetSunguralp commented on images/sekil1.png
Bu çiçekleri svg olarak export edebilirsin

2024-07-23 16:57 UTC, MehmetSunguralp commented on style.css
> +.collection{
Hero section'a ait olan her class adının önüne .hero-section class adını ekle ki sayfadaki diğer class isimleriyle karışmasın

2024-07-23 16:57 UTC, MehmetSunguralp commented on style.css
> +body{
background color body'ye değil sadece senin section'ına etki etmeli

2024-07-26 07:13 UTC, kubrakaramanli commented
Hero Section' da istenilen düzenlemeler gerçekleşti

2024-07-27 11:56 UTC, MehmetSunguralp commented
- master branch'deki dosyalar sende gözükmüyor
- proje adını içeren ayrı bi klasör var ve içi boş
- resimlerin direkt images klasörünün içinde bulunuyor, heroSection klasörünün içinde olması lazım
- hotSection adında boş bir klasör var
![image](https://github.com/user-attachments/assets/b42955fc-f858-42ea-b459-f25ce141c1b1)

2024-07-27 12:27 UTC, MehmetSunguralp requested changes
Tasarımdakine uymuyor tam olarak, kodlarını tekrar gözden geçirebilirsin

2024-07-27 12:27 UTC, MehmetSunguralp commented on index.html
> +		</div clas imeges>
kapanış etiketine class verilmiş

2024-07-27 12:27 UTC, MehmetSunguralp commented on style.css
> +	font-weight: 1920px;
font-weight:... değeri pixel değil 400, 500, 600, 700 vs. gibi indirdiğin font kalınlıklarına göre olmalı

2024-07-27 12:27 UTC, MehmetSunguralp commented on style.css
> +}*/
Yorum satırlarını silebilirsin

2024-07-27 12:27 UTC, MehmetSunguralp commented on style.css
> +	margin-top: 413px;
Bu değerler yerine sayfada ortalamak için sadece ``margin-inline: auto;` özelliği eklemelisin

2024-07-27 12:27 UTC, MehmetSunguralp commented on style.css
> +	left:2100px ;
left değeri yüzünden sayfadan taşıyor, onun yerine right: 0 kullanmalısın

2024-07-27 12:27 UTC, MehmetSunguralp commented on style.css
> +.herosectionbody{
max-width: 1920 px ve width: 100% değerleri eklemelisin.

Ayrıca çiçekleri hizalamak için position: relative özelliğini burada kullanmalısın

2024-07-27 12:27 UTC, MehmetSunguralp commented on style.css
> +	padding: 50px 10px 100px 10px;
font-weight: 300 olarak vermen lazım tasarımı baz alarak

2024-07-27 12:27 UTC, MehmetSunguralp commented on index.html
> +		<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
Bütün font kalınlıklarını indirmen lazım, şu an sadece 400 ve 700 var

2024-07-30 15:51 UTC, closed without merging